.TH "todo" 3 "Fri Apr 16 2021" "Version 0.0.1" "ASCII Table" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todoTodo List 
 \- 
.IP "\fBGlobal \fBASCIITable::dump\fP (void)\fP" 1c
write docs  
.IP "\fBGlobal \fBASCIITable::nline\fP \fP" 1c
check colcount / nline redundancy  
.IP "\fBGlobal \fBASCIITable::parserow\fP (char *mybuffer, int mncols)\fP" 1c
write docs  
.IP "\fBGlobal \fBASCIITable::read\fP (const FILE *inf)\fP" 1c
write docs  
.IP "\fBGlobal \fBASCIITable::~ASCIITable\fP (void)\fP" 1c
write docs 
.PP

